import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import NavbarComponent from "./navbar/page";
import FooterComponent from "./footer/page";

const bebasNeue = Bebas_Neue({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NOCAUT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bebasNeue.className}>
        <header>
          <NavbarComponent />
        </header>
        {children}
        <footer>
          <FooterComponent />
        </footer>
      </body>
    </html>
  );
}
